name: car_parking
description: "A new Flutter project."
publish_to: 'none' # هذا يمنع النشر إلى pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^9.0.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.5
  provider: ^6.0.5
  form_builder_validators: ^11.2.0
  intl_phone_field: ^3.2.0
  fluttertoast: ^8.2.4
  dio: ^5.8.0+1
  flutter_offline: ^5.0.0
  dartz: ^0.10.1
  uuid: ^4.5.1
  google_maps_flutter: ^2.2.3
  internet_connection_checker: ^3.0.1
  geolocator: ^14.0.2
  logging: ^1.3.0
  intl: ^0.20.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  crypto: ^3.0.0
  geocoding: ^2.1.1
  flutter_blue_plus: ^1.32.10
  flutter_nfc_kit: ^3.3.3
  ndef: ^0.3.4
  jwt_decoder: ^2.0.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  assets:
    - assets/certs/localhost.pem

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"